In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("/Users/eugene/Desktop/Emory/Projects/Travelers/data/raw/Training_TriGuard.csv")
df.head()

,subrogation,claim_number,year_of_born,gender,email_or_tel_available,safety_rating,annual_income,high_education_ind,address_change_ind,living_status,...,claim_est_payout,vehicle_made_year,vehicle_category,vehicle_price,vehicle_color,vehicle_weight,age_of_DL,accident_type,in_network_bodyshop,vehicle_mileage
0,1.0,6090851,1990.0,F,0.0,75.0,70966.0,1.0,1.0,Rent,...,3218.84,2021.0,Large,16272.12725,red,21620.79697,25.0,multi_vehicle_clear,no,75421.0
1,0.0,4653734,1972.0,F,1.0,94.0,79723.0,1.0,1.0,Rent,...,1338.52,2025.0,Medium,34102.78197,silver,10840.58520,23.0,multi_vehicle_clear,yes,31988.0
2,0.0,1014777,2003.0,F,1.0,76.0,41527.0,1.0,1.0,Own,...,3540.05,2022.0,Compact,15000.00000,silver,24318.12282,23.0,multi_vehicle_unclear,yes,60876.0
3,1.0,8101873,1983.0,F,1.0,54.0,42099.0,1.0,1.0,Rent,...,1507.94,2025.0,Medium,16984.45295,white,36958.26656,23.0,multi_vehicle_unclear,yes,152772.0
4,0.0,5081870,1985.0,F,1.0,54.0,47206.0,1.0,1.0,Own,...,5080.63,2021.0,Compact,46545.72863,blue,11779.17422,17.0,multi_vehicle_clear,yes,41151.0

In [3]:
df.shape

(18001, 29)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18001 entries, 0 to 18000
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   subrogation              17999 non-null  float64
 1   claim_number             18001 non-null  int64
 2   year_of_born             18000 non-null  float64
 3   gender                   18000 non-null  object
 4   email_or_tel_available   18000 non-null  float64
 5   safety_rating            18000 non-null  float64
 6   annual_income            18000 non-null  float64
 7   high_education_ind       18000 non-null  float64
 8   address_change_ind       18000 non-null  float64
 9   living_status            18000 non-null  object
 10  zip_code                 18000 non-null  float64
 11  claim_date               18000 non-null  object
 12  claim_day_of_week        18000 non-null  object
 13  accident_site            18000 non-null  object
 14  past_num_of_claims       18000 non-null  float64
 15  witness_present_ind      18000 non-null  object
 16  liab_prct                18000 non-null  float64
 17  channel                  18000 non-null  object
 18  policy_report_filed_ind  18000 non-null  float64
 19  claim_est_payout         18000 non-null  float64
 20  vehicle_made_year        18000 non-null  float64
 21  vehicle_category         18000 non-null  object
 22  vehicle_price            18000 non-null  float64
 23  vehicle_color            18000 non-null  object
 24  vehicle_weight           18000 non-null  float64
 25  age_of_DL                18000 non-null  float64
 26  accident_type            18000 non-null  object
 27  in_network_bodyshop      18000 non-null  object
 28  vehicle_mileage          18000 non-null  float64
dtypes: float64(17), int64(1), object(11)
memory usage: 4.0+ MB

# Handling null values

In [5]:
df.isna().sum()

subrogation                2
claim_number               0
year_of_born               1
gender                     1
email_or_tel_available     1
safety_rating              1
annual_income              1
high_education_ind         1
address_change_ind         1
living_status              1
zip_code                   1
claim_date                 1
claim_day_of_week          1
accident_site              1
past_num_of_claims         1
witness_present_ind        1
liab_prct                  1
channel                    1
policy_report_filed_ind    1
claim_est_payout           1
vehicle_made_year          1
vehicle_category           1
vehicle_price              1
vehicle_color              1
vehicle_weight             1
age_of_DL                  1
accident_type              1
in_network_bodyshop        1
vehicle_mileage            1
dtype: int64

In [6]:
# Dropping null values
df = df.dropna()

In [7]:
df.isna().sum()

subrogation                0
claim_number               0
year_of_born               0
gender                     0
email_or_tel_available     0
safety_rating              0
annual_income              0
high_education_ind         0
address_change_ind         0
living_status              0
zip_code                   0
claim_date                 0
claim_day_of_week          0
accident_site              0
past_num_of_claims         0
witness_present_ind        0
liab_prct                  0
channel                    0
policy_report_filed_ind    0
claim_est_payout           0
vehicle_made_year          0
vehicle_category           0
vehicle_price              0
vehicle_color              0
vehicle_weight             0
age_of_DL                  0
accident_type              0
in_network_bodyshop        0
vehicle_mileage            0
dtype: int64

In [8]:
df.shape

(17999, 29)

In [9]:
df[["annual_income", "vehicle_price", "vehicle_mileage"]].quantile([0.01, 0.99])

      annual_income  vehicle_price  vehicle_mileage
0.01        30015.0    15000.00000          9187.88
0.99       124993.0    94462.33841        150303.18

# Deleting columns that will not be used to train the model

In [10]:
# Delete one column ( Claim number)
df = df.drop("claim_number", axis=1)

# Changing Column datatypes

In [11]:
# Changing columns types
df["subrogation"] = df["subrogation"].astype(bool)

In [12]:
df["zip_code"] = df["zip_code"].astype("string")

In [13]:
df["claim_date"] = pd.to_datetime(df["claim_date"])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17999 entries, 0 to 18000
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   subrogation              17999 non-null  bool
 1   year_of_born             17999 non-null  float64
 2   gender                   17999 non-null  object
 3   email_or_tel_available   17999 non-null  float64
 4   safety_rating            17999 non-null  float64
 5   annual_income            17999 non-null  float64
 6   high_education_ind       17999 non-null  float64
 7   address_change_ind       17999 non-null  float64
 8   living_status            17999 non-null  object
 9   zip_code                 17999 non-null  string
 10  claim_date               17999 non-null  datetime64[ns]
 11  claim_day_of_week        17999 non-null  object
 12  accident_site            17999 non-null  object
 13  past_num_of_claims       17999 non-null  float64
 14  witness_present_ind      17999 non-null  object
 15  liab_prct                17999 non-null  float64
 16  channel                  17999 non-null  object
 17  policy_report_filed_ind  17999 non-null  float64
 18  claim_est_payout         17999 non-null  float64
 19  vehicle_made_year        17999 non-null  float64
 20  vehicle_category         17999 non-null  object
 21  vehicle_price            17999 non-null  float64
 22  vehicle_color            17999 non-null  object
 23  vehicle_weight           17999 non-null  float64
 24  age_of_DL                17999 non-null  float64
 25  accident_type            17999 non-null  object
 26  in_network_bodyshop      17999 non-null  object
 27  vehicle_mileage          17999 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(15), object(10), string(1)
memory usage: 3.9+ MB

# Transforming floats to boolean

In [15]:
df[["email_or_tel_available", "high_education_ind", "address_change_ind", "policy_report_filed_ind"]].head()

,email_or_tel_available,high_education_ind,address_change_ind,policy_report_filed_ind
0,0.0,1.0,1.0,1.0
1,1.0,1.0,1.0,1.0
2,1.0,1.0,1.0,1.0
3,1.0,1.0,1.0,1.0
4,1.0,1.0,1.0,0.0

In [16]:
# Transforming binary columns from float to boolean
# ["email_or_tel_available", "high_education_ind", "address_change_ind", "policy_report_filed_ind"]
df["email_or_tel_available"] = df["email_or_tel_available"].astype(bool)
df["high_education_ind"] = df["high_education_ind"].astype(bool)
df["address_change_ind"] = df["address_change_ind"].astype(bool)
df["policy_report_filed_ind"] = df["policy_report_filed_ind"].astype(bool)

In [17]:
df[["email_or_tel_available", "high_education_ind", "address_change_ind", "policy_report_filed_ind"]].head()

,email_or_tel_available,high_education_ind,address_change_ind,policy_report_filed_ind
0,False,True,True,True
1,True,True,True,True
2,True,True,True,True
3,True,True,True,True
4,True,True,True,False

# Handling the Yes/No columns

In [18]:
df[['witness_present_ind', 'in_network_bodyshop']].head()

  witness_present_ind in_network_bodyshop
0                   Y                  no
1                   N                 yes
2                   N                 yes
3                   N                 yes
4                   N                 yes

In [19]:
# Transforming yes/no questions to 1/0
# ['witness_present_ind', 'in_network_bodyshop']
# Convert Y/N and yes/no to boolean True/False
df["witness_present_ind"] = df["witness_present_ind"].str.upper().map({'Y': True, 'N': False})
df["in_network_bodyshop"] = df["in_network_bodyshop"].str.lower().map({'yes': True, 'no': False})
df[['witness_present_ind', 'in_network_bodyshop']].head()

   witness_present_ind  in_network_bodyshop
0                 True                False
1                False                 True
2                False                 True
3                False                 True
4                False                 True

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17999 entries, 0 to 18000
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   subrogation              17999 non-null  bool
 1   year_of_born             17999 non-null  float64
 2   gender                   17999 non-null  object
 3   email_or_tel_available   17999 non-null  bool
 4   safety_rating            17999 non-null  float64
 5   annual_income            17999 non-null  float64
 6   high_education_ind       17999 non-null  bool
 7   address_change_ind       17999 non-null  bool
 8   living_status            17999 non-null  object
 9   zip_code                 17999 non-null  string
 10  claim_date               17999 non-null  datetime64[ns]
 11  claim_day_of_week        17999 non-null  object
 12  accident_site            17999 non-null  object
 13  past_num_of_claims       17999 non-null  float64
 14  witness_present_ind      17999 non-null  bool
 15  liab_prct                17999 non-null  float64
 16  channel                  17999 non-null  object
 17  policy_report_filed_ind  17999 non-null  bool
 18  claim_est_payout         17999 non-null  float64
 19  vehicle_made_year        17999 non-null  float64
 20  vehicle_category         17999 non-null  object
 21  vehicle_price            17999 non-null  float64
 22  vehicle_color            17999 non-null  object
 23  vehicle_weight           17999 non-null  float64
 24  age_of_DL                17999 non-null  float64
 25  accident_type            17999 non-null  object
 26  in_network_bodyshop      17999 non-null  bool
 27  vehicle_mileage          17999 non-null  float64
dtypes: bool(7), datetime64[ns](1), float64(11), object(8), string(1)
memory usage: 3.1+ MB

# Handing the Zip code column

In [21]:
# Delete one column ( zip_code)
df = df.drop("zip_code", axis=1)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17999 entries, 0 to 18000
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   subrogation              17999 non-null  bool
 1   year_of_born             17999 non-null  float64
 2   gender                   17999 non-null  object
 3   email_or_tel_available   17999 non-null  bool
 4   safety_rating            17999 non-null  float64
 5   annual_income            17999 non-null  float64
 6   high_education_ind       17999 non-null  bool
 7   address_change_ind       17999 non-null  bool
 8   living_status            17999 non-null  object
 9   claim_date               17999 non-null  datetime64[ns]
 10  claim_day_of_week        17999 non-null  object
 11  accident_site            17999 non-null  object
 12  past_num_of_claims       17999 non-null  float64
 13  witness_present_ind      17999 non-null  bool
 14  liab_prct                17999 non-null  float64
 15  channel                  17999 non-null  object
 16  policy_report_filed_ind  17999 non-null  bool
 17  claim_est_payout         17999 non-null  float64
 18  vehicle_made_year        17999 non-null  float64
 19  vehicle_category         17999 non-null  object
 20  vehicle_price            17999 non-null  float64
 21  vehicle_color            17999 non-null  object
 22  vehicle_weight           17999 non-null  float64
 23  age_of_DL                17999 non-null  float64
 24  accident_type            17999 non-null  object
 25  in_network_bodyshop      17999 non-null  bool
 26  vehicle_mileage          17999 non-null  float64
dtypes: bool(7), datetime64[ns](1), float64(11), object(8)
memory usage: 3.0+ MB

In [23]:
df.head()

,subrogation,year_of_born,gender,email_or_tel_available,safety_rating,annual_income,high_education_ind,address_change_ind,living_status,claim_date,...,claim_est_payout,vehicle_made_year,vehicle_category,vehicle_price,vehicle_color,vehicle_weight,age_of_DL,accident_type,in_network_bodyshop,vehicle_mileage
0,True,1990.0,F,False,75.0,70966.0,True,True,Rent,2016-12-04,...,3218.84,2021.0,Large,16272.12725,red,21620.79697,25.0,multi_vehicle_clear,False,75421.0
1,False,1972.0,F,True,94.0,79723.0,True,True,Rent,2015-04-25,...,1338.52,2025.0,Medium,34102.78197,silver,10840.58520,23.0,multi_vehicle_clear,True,31988.0
2,False,2003.0,F,True,76.0,41527.0,True,True,Own,2015-06-22,...,3540.05,2022.0,Compact,15000.00000,silver,24318.12282,23.0,multi_vehicle_unclear,True,60876.0
3,True,1983.0,F,True,54.0,42099.0,True,True,Rent,2015-03-02,...,1507.94,2025.0,Medium,16984.45295,white,36958.26656,23.0,multi_vehicle_unclear,True,152772.0
4,False,1985.0,F,True,54.0,47206.0,True,True,Own,2016-01-12,...,5080.63,2021.0,Compact,46545.72863,blue,11779.17422,17.0,multi_vehicle_clear,True,41151.0